# Generated by Django 3.2 on 2021-12-14 16:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='E.g. "Downtown billboard"', max_length=100)),
                ('incoming_number', phonenumber_field.modelfields.PhoneNumberField(help_text='A phone number purchased through Twilio', max_length=128, unique=True)),
                ('forwarding_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='People who call this lead source will be connected with this phone number. Must include international prefix - e.g. +1 555 555 55555', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_tracking.leadsource')),
            ],
        ),
    ]
